version: "2"

#volumes:
#  data-www:
#  data-mysql:
#  data-redis:

services:
  
  # vhosts
  vhosts:
    build:
      context: ./docker/vhosts
      dockerfile: Dockerfile
    restart: always
    container_name: vhosts
    hostname: vhosts
    working_dir: /www
    volumes: 
      - "./data/www:/www"
    links:
      - mysql
      - redis
      - memcached
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"

  # backup
  #backup:
  #  image: tenstartups/backup-service

  # samba
  samba:
    image: dperson/samba
    restart: always
    container_name: samba
    hostname: samba
    environment:
      USERID: 1000
      GROUPID: 1000
      USER: "user;user"
      SHARE: "www;/mount;yes;yes;yes;all"
      RECYCLE: true
    volumes:
      - "./data/www:/mount"
    ports:
      - "445:445"
      - "139:139"

  # database
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    hostname: mysql
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=krasnal
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    hostname: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8080:80"
    links: 
      - mysql

  # Cache - Redis
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    hostname: redis
    working_dir: /data
    volumes:
      - "./data/redis:/data"
    ports:
      - "6379:6379"
  
  # Cache memcached
  memcached:
    image: memcached:latest
    restart: always
    container_name: memcached
    hostname: memcached
    ports:
      - "11211:11211"
